@echo off
setlocal
REM Build a single portable, OFFLINE esu_test.exe (run on Windows, needs Python once here).
REM Driver on target PCs = Zadig -> bind scope USBTMC interface to WinUSB. No NI-VISA.
REM
REM This file is the ONLY source of truth for the build. esu_test.spec is REGENERATED by the
REM command below on every run and is gitignored -- do not edit it expecting the change to stick.
REM
REM Note on style: every failure check is a parenthesised block, never `if errorlevel 1 a & b`.
REM In cmd, `&` splits at the top level, so the second command runs whether the `if` fired or
REM not -- an `exit /b 1` written that way ends the script on a SUCCESSFUL step.

REM `python -m PyInstaller`, not `pyinstaller`: the console script is not always on PATH even
REM when the package is installed, and the bare name fails with a message that scrolls past.
python -m pip install -r requirements.txt libusb-package pyinstaller
if errorlevel 1 (
    echo.
    echo FAILED: pip install did not complete.
    exit /b 1
)

REM Grab the bundled libusb-1.0.dll from the libusb-package wheel (offline after pip).
python -c "import libusb_package,glob,os,shutil,sys; f=glob.glob(os.path.join(os.path.dirname(libusb_package.__file__),'**','libusb-1.0.dll'),recursive=True); shutil.copy(f[0],'.') if f else sys.exit('libusb-1.0.dll not found - drop it here manually from libusb.info')"
if errorlevel 1 (
    echo.
    echo FAILED: could not obtain libusb-1.0.dll.
    exit /b 1
)

REM Delete the old exe FIRST, so a failed build cannot leave the previous one sitting there
REM looking like a fresh result. That is exactly what used to happen: without --noconfirm,
REM PyInstaller prompts "output directory ... will be REMOVED! Continue? (y/N)" whenever dist\
REM already exists, defaults to N, aborts -- and the old script still printed "Done."
if exist "dist\esu_test.exe" del /q "dist\esu_test.exe"

REM --noconfirm = never prompt.  --clean = no stale build cache.
REM --windowed  = no background console when techs double-click the wizard.
REM (CLI text modes like --calcheck/--list still run, but print nowhere on the exe; run those from `python esu_test.py`.)
python -m PyInstaller --noconfirm --clean --onefile --windowed ^
  --collect-all pyvisa --collect-all pyvisa_py --collect-all usb ^
  --add-binary "libusb-1.0.dll;." ^
  --add-data "refs/*.csv;refs" ^
  esu_test.py
if errorlevel 1 (
    echo.
    echo FAILED: PyInstaller returned an error -- read the log above.
    exit /b 1
)
if not exist "dist\esu_test.exe" (
    echo.
    echo FAILED: PyInstaller reported success but dist\esu_test.exe is not there.
    echo If the exe was running, close it and build again -- Windows locks a running exe.
    exit /b 1
)

echo.
echo Done. Single file is dist\esu_test.exe  -- copy it anywhere.
dir "dist\esu_test.exe" | findstr /i "esu_test.exe"
echo.
echo Machine profiles the wizard saves land in a refs\ folder NEXT TO the exe.
echo On each target PC once: run Zadig, pick the scope USBTMC interface, Install WinUSB.
echo Then run:  esu_test.exe --list   to confirm the scope is seen.
